## Python Libraries For Data Science
* Data science is the process of deriving knowledge and insights from a huge and diverse set of data through organizing, processing and analysing the data.
* There are nearly 20 python libraries for Data Science. Top five python libraries are
* TensorFlow
* NumPy
* SciPy
* Pandas
* Matplotlib
* In those libraries, Numpy and Pandas are the first choice to the data scientists who are aware of the technologies.

## NumPy: (Numerical Python)¶
* Numpy is Base N-Dimensional Array Package, is a python library and a fundamental package for scientific computing in Python. It is used to create multidimensional arrays for fast operations. Use the following import conversion.
* import numpy as np

## Introduction to NumPy
* The learning objectives of this section are:
* Understand advantages of vectorised code using NumPy (over standard python ways)
* Create NumPy arrays
* Convert lists and tuples to NumPy arrays
* Create (initialise) arrays
* Inspect the structure and content of arrays
* Subset, slice, index and iterate through arrays
* Compare computation times in NumPy and standard Python lists
* There are 3 arrys 1d array,2d array,3d array

In [71]:
import numpy as np

In [15]:
np.array([1,2,3])

array([1, 2, 3])

In [16]:
np.array([1])

array([1])

In [17]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [18]:
type(a)

numpy.ndarray

In [19]:
arr_2d = np.array([[1,2,3],[2,3,4]])
arr_2d

array([[1, 2, 3],
       [2, 3, 4]])

In [20]:
type(arr_2d)

numpy.ndarray

In [21]:
arr_3d = np.array([[[1,2],[2,5],[3,6]]])
arr_3d

array([[[1, 2],
        [2, 5],
        [3, 6]]])

In [22]:
l1=[1,2,3,4]
#l1**2
# 1,4,9,16
l2=[]
for i in l1:
    l2.append(i**2)
l2

[1, 4, 9, 16]

In [23]:
%time
res=lambda x : x**2
list(map(res,l1))

Wall time: 0 ns


[1, 4, 9, 16]

In [24]:
[i**2 for i in l1]

[1, 4, 9, 16]

In [35]:
s1 = np.array([1,2,3,4])
s1**2

array([ 1,  4,  9, 16], dtype=int32)

In [26]:
s2 = np.array([3,4,5,6])
s1+s2

array([ 4,  6,  8, 10])

In [36]:
s1

array([1, 2, 3, 4])

In [37]:
%time
s1/s2

Wall time: 0 ns


array([0.33333333, 0.5       , 0.6       , 0.66666667])

In [38]:
s1+s2

array([ 4,  6,  8, 10])

In [39]:
s1

array([1, 2, 3, 4])

In [40]:
s1[0]

1

In [41]:
s1[1]

2

In [42]:
arr_2d

array([[1, 2, 3],
       [2, 3, 4]])

In [43]:
arr_2d[0][2]

3

In [44]:
r = range(0,10,2)
type(r)

range

In [45]:
a = np.arange(10)
a
type(a)

numpy.ndarray

In [46]:
a1 = np.arange(1,10,2)
a1

array([1, 3, 5, 7, 9])

In [47]:
a2 = np.array(range(1,10,2))
a2

array([1, 3, 5, 7, 9])

In [48]:
a3 = np.linspace(1,10,100)
a3

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

In [49]:
range(1.5,10.5)

TypeError: 'float' object cannot be interpreted as an integer

In [50]:
a1 = np.arange(1.5,10.5,2)
a1

array([1.5, 3.5, 5.5, 7.5, 9.5])

In [51]:
a2 = np.linspace(1.2,90.4,10)
a2

array([ 1.2       , 11.11111111, 21.02222222, 30.93333333, 40.84444444,
       50.75555556, 60.66666667, 70.57777778, 80.48888889, 90.4       ])

In [52]:
type(a2[0])

numpy.float64

In [53]:
arr_3d

array([[[1, 2],
        [2, 5],
        [3, 6]]])

In [54]:
arr_3d.reshape(2,3)

array([[1, 2, 2],
       [5, 3, 6]])

In [56]:
arr_3d.reshape(4)

ValueError: cannot reshape array of size 6 into shape (4,)

In [57]:
arr_3d.reshape(-1)

array([1, 2, 2, 5, 3, 6])

In [58]:
arr_3d.reshape(3,-1)

array([[1, 2],
       [2, 5],
       [3, 6]])

In [59]:
arr_3d.reshape(-1,3)

array([[1, 2, 2],
       [5, 3, 6]])

In [60]:
arr_3d

array([[[1, 2],
        [2, 5],
        [3, 6]]])

In [61]:
arr_3d.reshape(3,-1)

array([[1, 2],
       [2, 5],
       [3, 6]])

In [62]:
arr_3d.reshape(-1,2)

array([[1, 2],
       [2, 5],
       [3, 6]])

In [63]:
arr_3d.reshape(2,-1)

array([[1, 2, 2],
       [5, 3, 6]])

In [64]:

arr_3d.reshape(-1)

array([1, 2, 2, 5, 3, 6])

In [65]:
a =np.array([[[1,2,3],[4,5,6]],[[3,4,5],[5,6,7]]])
a

array([[[1, 2, 3],
        [4, 5, 6]],

       [[3, 4, 5],
        [5, 6, 7]]])

In [66]:
a.itemsize

4

In [67]:
a.ndim

3

In [68]:
a.shape

(2, 2, 3)

In [130]:
dir(numpy)

NameError: name 'numpy' is not defined

In [73]:
help(np.shape)

Help on function shape in module numpy:

shape(a)
    Return the shape of an array.
    
    Parameters
    ----------
    a : array_like
        Input array.
    
    Returns
    -------
    shape : tuple of ints
        The elements of the shape tuple give the lengths of the
        corresponding array dimensions.
    
    See Also
    --------
    alen
    ndarray.shape : Equivalent array method.
    
    Examples
    --------
    >>> np.shape(np.eye(3))
    (3, 3)
    >>> np.shape([[1, 2]])
    (1, 2)
    >>> np.shape([0])
    (1,)
    >>> np.shape(0)
    ()
    
    >>> a = np.array([(1, 2), (3, 4)], dtype=[('x', 'i4'), ('y', 'i4')])
    >>> np.shape(a)
    (2,)
    >>> a.shape
    (2,)



In [75]:
d = np.arange(1,500,9)

In [76]:
d

array([  1,  10,  19,  28,  37,  46,  55,  64,  73,  82,  91, 100, 109,
       118, 127, 136, 145, 154, 163, 172, 181, 190, 199, 208, 217, 226,
       235, 244, 253, 262, 271, 280, 289, 298, 307, 316, 325, 334, 343,
       352, 361, 370, 379, 388, 397, 406, 415, 424, 433, 442, 451, 460,
       469, 478, 487, 496])

In [77]:
d[55]# 0 - 55

496

In [78]:
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [79]:
np.ones((10,10),dtype=int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [80]:
np.zeros((2,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [82]:
np.eye(2,2)

array([[1., 0.],
       [0., 1.]])

In [83]:
np.eye(100,100)

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [84]:
np.eye((10),dtype=int)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [85]:
np.eye((10),k=5)

array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [86]:
np.eye((10),k=-5)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]])

In [87]:
a

array([[[1, 2, 3],
        [4, 5, 6]],

       [[3, 4, 5],
        [5, 6, 7]]])

In [88]:
a.T

array([[[1, 3],
        [4, 5]],

       [[2, 4],
        [5, 6]],

       [[3, 5],
        [6, 7]]])

In [89]:
a2

array([ 1.2       , 11.11111111, 21.02222222, 30.93333333, 40.84444444,
       50.75555556, 60.66666667, 70.57777778, 80.48888889, 90.4       ])

In [90]:
a2.T

array([ 1.2       , 11.11111111, 21.02222222, 30.93333333, 40.84444444,
       50.75555556, 60.66666667, 70.57777778, 80.48888889, 90.4       ])

In [91]:
a1

array([1.5, 3.5, 5.5, 7.5, 9.5])

In [92]:
a1.T

array([1.5, 3.5, 5.5, 7.5, 9.5])

In [93]:
help(np.transpose)

Help on function transpose in module numpy:

transpose(a, axes=None)
    Permute the dimensions of an array.
    
    Parameters
    ----------
    a : array_like
        Input array.
    axes : list of ints, optional
        By default, reverse the dimensions, otherwise permute the axes
        according to the values given.
    
    Returns
    -------
    p : ndarray
        `a` with its axes permuted.  A view is returned whenever
        possible.
    
    See Also
    --------
    moveaxis
    argsort
    
    Notes
    -----
    Use `transpose(a, argsort(axes))` to invert the transposition of tensors
    when using the `axes` keyword argument.
    
    Transposing a 1-D array returns an unchanged view of the original array.
    
    Examples
    --------
    >>> x = np.arange(4).reshape((2,2))
    >>> x
    array([[0, 1],
           [2, 3]])
    
    >>> np.transpose(x)
    array([[0, 2],
           [1, 3]])
    
    >>> x = np.ones((1, 2, 3))
    >>> np.transpose(x, (1, 0, 2)).s

In [94]:
np.transpose(a1)

array([1.5, 3.5, 5.5, 7.5, 9.5])

In [96]:
a = [[1,2],[3,4]]
a

[[1, 2], [3, 4]]

In [95]:
np.transpose(a)

array([[[1, 3],
        [4, 5]],

       [[2, 4],
        [5, 6]],

       [[3, 5],
        [6, 7]]])

In [97]:
np.random.random((2,10))

array([[0.46244902, 0.62602246, 0.78820685, 0.16473296, 0.35999722,
        0.95948432, 0.92713898, 0.83483773, 0.23403519, 0.68741655],
       [0.22535712, 0.46839467, 0.44269084, 0.50384097, 0.12573433,
        0.21099992, 0.15298351, 0.96906039, 0.72713757, 0.60643797]])

In [98]:
f = np.random.randint(100,500,(25,6))
f

array([[481, 478, 254, 139, 347, 104],
       [127, 475, 290, 272, 395, 352],
       [266, 487, 108, 356, 387, 244],
       [327, 448, 372, 261, 157, 158],
       [354, 495, 156, 106, 445, 223],
       [223, 468, 116, 375, 478, 149],
       [178, 248, 391, 415, 429, 104],
       [402, 100, 213, 214, 425, 372],
       [325, 405, 246, 325, 115, 253],
       [211, 380, 234, 262, 158, 183],
       [132, 243, 147, 199, 317, 376],
       [193, 263, 461, 340, 106, 115],
       [327, 354, 191, 345, 289, 189],
       [279, 144, 263, 109, 192, 479],
       [499, 381, 360, 113, 194, 131],
       [151, 215, 354, 485, 345, 183],
       [165, 403, 125, 203, 349, 427],
       [299, 339, 442, 146, 127, 162],
       [218, 444, 221, 180, 106, 375],
       [106, 107, 478, 147, 291, 100],
       [151, 360, 449, 443, 433, 224],
       [237, 166, 465, 344, 215, 327],
       [213, 237, 169, 342, 363, 243],
       [494, 166, 142, 218, 414, 380],
       [294, 285, 371, 495, 245, 366]])

In [99]:
f.shape

(25, 6)

In [100]:
f[1:]

array([[127, 475, 290, 272, 395, 352],
       [266, 487, 108, 356, 387, 244],
       [327, 448, 372, 261, 157, 158],
       [354, 495, 156, 106, 445, 223],
       [223, 468, 116, 375, 478, 149],
       [178, 248, 391, 415, 429, 104],
       [402, 100, 213, 214, 425, 372],
       [325, 405, 246, 325, 115, 253],
       [211, 380, 234, 262, 158, 183],
       [132, 243, 147, 199, 317, 376],
       [193, 263, 461, 340, 106, 115],
       [327, 354, 191, 345, 289, 189],
       [279, 144, 263, 109, 192, 479],
       [499, 381, 360, 113, 194, 131],
       [151, 215, 354, 485, 345, 183],
       [165, 403, 125, 203, 349, 427],
       [299, 339, 442, 146, 127, 162],
       [218, 444, 221, 180, 106, 375],
       [106, 107, 478, 147, 291, 100],
       [151, 360, 449, 443, 433, 224],
       [237, 166, 465, 344, 215, 327],
       [213, 237, 169, 342, 363, 243],
       [494, 166, 142, 218, 414, 380],
       [294, 285, 371, 495, 245, 366]])

In [101]:
f[3]

array([327, 448, 372, 261, 157, 158])

In [102]:
f[[3,4,5]]

array([[327, 448, 372, 261, 157, 158],
       [354, 495, 156, 106, 445, 223],
       [223, 468, 116, 375, 478, 149]])

In [103]:
f[-5:]

array([[151, 360, 449, 443, 433, 224],
       [237, 166, 465, 344, 215, 327],
       [213, 237, 169, 342, 363, 243],
       [494, 166, 142, 218, 414, 380],
       [294, 285, 371, 495, 245, 366]])

In [104]:
f[:2]

array([[481, 478, 254, 139, 347, 104],
       [127, 475, 290, 272, 395, 352]])

In [105]:
f[2,[2,3]]

array([108, 356])

In [106]:
f[[2,3,4],[2,3,4]]

array([108, 261, 445])

In [107]:
a

[[1, 2], [3, 4]]

In [108]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [109]:
np.exp(a)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [110]:
np.sin(a)

array([[ 0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 ]])

In [111]:
np.log(a)

array([[0.        , 0.69314718],
       [1.09861229, 1.38629436]])

In [112]:
np.linalg.det(a)

-2.0000000000000004

In [113]:
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [114]:
np.linalg.eig(a)

(array([-0.37228132,  5.37228132]), array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

In [115]:
a

[[1, 2], [3, 4]]

In [116]:
np.full((1,3),10)

array([[10, 10, 10]])

In [117]:
s = np.array([[[1,2],[9,8]],[[1,2],[7,8]]])
s

array([[[1, 2],
        [9, 8]],

       [[1, 2],
        [7, 8]]])

In [118]:
s.flatten()

array([1, 2, 9, 8, 1, 2, 7, 8])

In [119]:
help(np.tile)

Help on function tile in module numpy:

tile(A, reps)
    Construct an array by repeating A the number of times given by reps.
    
    If `reps` has length ``d``, the result will have dimension of
    ``max(d, A.ndim)``.
    
    If ``A.ndim < d``, `A` is promoted to be d-dimensional by prepending new
    axes. So a shape (3,) array is promoted to (1, 3) for 2-D replication,
    or shape (1, 1, 3) for 3-D replication. If this is not the desired
    behavior, promote `A` to d-dimensions manually before calling this
    function.
    
    If ``A.ndim > d``, `reps` is promoted to `A`.ndim by pre-pending 1's to it.
    Thus for an `A` of shape (2, 3, 4, 5), a `reps` of (2, 2) is treated as
    (1, 1, 2, 2).
    
    Note : Although tile may be used for broadcasting, it is strongly
    recommended to use numpy's broadcasting operations and functions.
    
    Parameters
    ----------
    A : array_like
        The input array.
    reps : array_like
        The number of repetitions of `A`

In [120]:
np.tile(s,4)

array([[[1, 2, 1, 2, 1, 2, 1, 2],
        [9, 8, 9, 8, 9, 8, 9, 8]],

       [[1, 2, 1, 2, 1, 2, 1, 2],
        [7, 8, 7, 8, 7, 8, 7, 8]]])

In [121]:
s

array([[[1, 2],
        [9, 8]],

       [[1, 2],
        [7, 8]]])

In [122]:
s.reshape(2,-1) # function

array([[1, 2, 9, 8],
       [1, 2, 7, 8]])

In [123]:
s.size # Attribute

8

In [124]:
s

array([[[1, 2],
        [9, 8]],

       [[1, 2],
        [7, 8]]])

In [125]:
import math

In [126]:
math.pi # package.attribute

3.141592653589793

In [127]:
math.pow(2,3) # package.function

8.0

In [128]:
dir(math)

['__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'acos',
 'acosh',
 'asin',
 'asinh',
 'atan',
 'atan2',
 'atanh',
 'ceil',
 'copysign',
 'cos',
 'cosh',
 'degrees',
 'e',
 'erf',
 'erfc',
 'exp',
 'expm1',
 'fabs',
 'factorial',
 'floor',
 'fmod',
 'frexp',
 'fsum',
 'gamma',
 'gcd',
 'hypot',
 'inf',
 'isclose',
 'isfinite',
 'isinf',
 'isnan',
 'ldexp',
 'lgamma',
 'log',
 'log10',
 'log1p',
 'log2',
 'modf',
 'nan',
 'pi',
 'pow',
 'radians',
 'remainder',
 'sin',
 'sinh',
 'sqrt',
 'tan',
 'tanh',
 'tau',
 'trunc']

In [129]:
help(math.tan)

Help on built-in function tan in module math:

tan(x, /)
    Return the tangent of x (measured in radians).

